name: Continuous Integration

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]
    tags: ["v*"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Package and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 17

      - name: Generate artifacts
        run: |
          ./mill -i show check
          ./mill -i __.publishArtifacts

      - name: Publish ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ./mill -i io.kipp.mill.ci.release.ReleaseModule/publishAll
        env:
          PGP_PASSPHRASE: ""
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.S01_SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.S01_SONATYPE_USERNAME }}
